# generated from resources.py.mako
# do not edit manually!
# flake8: noqa
# fmt: off
from trezor.utils import halt

# this module should not be part of the build, its purpose is only to add missed Qstrings
halt("Tried to import excluded module.")

import all_modules
import boot
import main
import protobuf
import register_messages
import session
import usb
import trezor
import trezor.crypto
import trezor.crypto.base32
import trezor.crypto.base58
import trezor.crypto.bech32
import trezor.crypto.cashaddr
import trezor.crypto.curve
import trezor.crypto.der
import trezor.crypto.hashlib
import trezor.crypto.rlp
import trezor.crypto.scripts
import trezor.crypto.slip39
import trezor.errors
import trezor.log
import trezor.loop
import trezor.messages.Address
import trezor.messages.AmountUnit
import trezor.messages.ApplyFlags
import trezor.messages.ApplySettings
import trezor.messages.AuthorizeCoinJoin
import trezor.messages.BackupDevice
import trezor.messages.BackupType
import trezor.messages.BinanceAddress
import trezor.messages.BinanceCancelMsg
import trezor.messages.BinanceCoin
import trezor.messages.BinanceGetAddress
import trezor.messages.BinanceGetPublicKey
import trezor.messages.BinanceInputOutput
import trezor.messages.BinanceOrderMsg
import trezor.messages.BinanceOrderSide
import trezor.messages.BinanceOrderType
import trezor.messages.BinancePublicKey
import trezor.messages.BinanceSignTx
import trezor.messages.BinanceSignedTx
import trezor.messages.BinanceTimeInForce
import trezor.messages.BinanceTransferMsg
import trezor.messages.BinanceTxRequest
import trezor.messages.ButtonAck
import trezor.messages.ButtonRequest
import trezor.messages.ButtonRequestType
import trezor.messages.Cancel
import trezor.messages.CancelAuthorization
import trezor.messages.Capability
import trezor.messages.CardanoAddress
import trezor.messages.CardanoAddressParametersType
import trezor.messages.CardanoAddressType
import trezor.messages.CardanoAssetGroupType
import trezor.messages.CardanoBlockchainPointerType
import trezor.messages.CardanoCertificateType
import trezor.messages.CardanoGetAddress
import trezor.messages.CardanoGetPublicKey
import trezor.messages.CardanoPoolMetadataType
import trezor.messages.CardanoPoolOwnerType
import trezor.messages.CardanoPoolParametersType
import trezor.messages.CardanoPoolRelayParametersType
import trezor.messages.CardanoPoolRelayType
import trezor.messages.CardanoPublicKey
import trezor.messages.CardanoSignTx
import trezor.messages.CardanoSignedTx
import trezor.messages.CardanoTokenType
import trezor.messages.CardanoTxCertificateType
import trezor.messages.CardanoTxInputType
import trezor.messages.CardanoTxOutputType
import trezor.messages.CardanoTxWithdrawalType
import trezor.messages.ChangePin
import trezor.messages.ChangeWipeCode
import trezor.messages.CipherKeyValue
import trezor.messages.CipheredKeyValue
import trezor.messages.DebugLinkDecision
import trezor.messages.DebugLinkEraseSdCard
import trezor.messages.DebugLinkGetState
import trezor.messages.DebugLinkLayout
import trezor.messages.DebugLinkRecordScreen
import trezor.messages.DebugLinkReseedRandom
import trezor.messages.DebugLinkShowText
import trezor.messages.DebugLinkShowTextItem
import trezor.messages.DebugLinkShowTextStyle
import trezor.messages.DebugLinkState
import trezor.messages.DebugLinkWatchLayout
import trezor.messages.DebugMoneroDiagAck
import trezor.messages.DebugMoneroDiagRequest
import trezor.messages.DebugSwipeDirection
import trezor.messages.Deprecated_PassphraseStateAck
import trezor.messages.Deprecated_PassphraseStateRequest
import trezor.messages.DoPreauthorized
import trezor.messages.ECDHSessionKey
import trezor.messages.EndSession
import trezor.messages.Entropy
import trezor.messages.EntropyAck
import trezor.messages.EntropyRequest
import trezor.messages.EosActionBuyRam
import trezor.messages.EosActionBuyRamBytes
import trezor.messages.EosActionCommon
import trezor.messages.EosActionDelegate
import trezor.messages.EosActionDeleteAuth
import trezor.messages.EosActionLinkAuth
import trezor.messages.EosActionNewAccount
import trezor.messages.EosActionRefund
import trezor.messages.EosActionSellRam
import trezor.messages.EosActionTransfer
import trezor.messages.EosActionUndelegate
import trezor.messages.EosActionUnknown
import trezor.messages.EosActionUnlinkAuth
import trezor.messages.EosActionUpdateAuth
import trezor.messages.EosActionVoteProducer
import trezor.messages.EosAsset
import trezor.messages.EosAuthorization
import trezor.messages.EosAuthorizationAccount
import trezor.messages.EosAuthorizationKey
import trezor.messages.EosAuthorizationWait
import trezor.messages.EosGetPublicKey
import trezor.messages.EosPermissionLevel
import trezor.messages.EosPublicKey
import trezor.messages.EosSignTx
import trezor.messages.EosSignedTx
import trezor.messages.EosTxActionAck
import trezor.messages.EosTxActionRequest
import trezor.messages.EosTxHeader
import trezor.messages.EthereumAddress
import trezor.messages.EthereumGetAddress
import trezor.messages.EthereumGetPublicKey
import trezor.messages.EthereumMessageSignature
import trezor.messages.EthereumPublicKey
import trezor.messages.EthereumSignMessage
import trezor.messages.EthereumSignTx
import trezor.messages.EthereumTxAck
import trezor.messages.EthereumTxRequest
import trezor.messages.EthereumVerifyMessage
import trezor.messages.Failure
import trezor.messages.FailureType
import trezor.messages.Features
import trezor.messages.GetAddress
import trezor.messages.GetECDHSessionKey
import trezor.messages.GetEntropy
import trezor.messages.GetFeatures
import trezor.messages.GetNextU2FCounter
import trezor.messages.GetOwnershipId
import trezor.messages.GetOwnershipProof
import trezor.messages.GetPublicKey
import trezor.messages.HDNodePathType
import trezor.messages.HDNodeType
import trezor.messages.IdentityType
import trezor.messages.Initialize
import trezor.messages.InputScriptType
import trezor.messages.LiskAddress
import trezor.messages.LiskDelegateType
import trezor.messages.LiskGetAddress
import trezor.messages.LiskGetPublicKey
import trezor.messages.LiskMessageSignature
import trezor.messages.LiskMultisignatureType
import trezor.messages.LiskPublicKey
import trezor.messages.LiskSignMessage
import trezor.messages.LiskSignTx
import trezor.messages.LiskSignatureType
import trezor.messages.LiskSignedTx
import trezor.messages.LiskTransactionAsset
import trezor.messages.LiskTransactionCommon
import trezor.messages.LiskTransactionType
import trezor.messages.LiskVerifyMessage
import trezor.messages.LoadDevice
import trezor.messages.LockDevice
import trezor.messages.MessageSignature
import trezor.messages.MessageType
import trezor.messages.MoneroAccountPublicAddress
import trezor.messages.MoneroAddress
import trezor.messages.MoneroExportedKeyImage
import trezor.messages.MoneroGetAddress
import trezor.messages.MoneroGetTxKeyAck
import trezor.messages.MoneroGetTxKeyRequest
import trezor.messages.MoneroGetWatchKey
import trezor.messages.MoneroKeyImageExportInitAck
import trezor.messages.MoneroKeyImageExportInitRequest
import trezor.messages.MoneroKeyImageSyncFinalAck
import trezor.messages.MoneroKeyImageSyncFinalRequest
import trezor.messages.MoneroKeyImageSyncStepAck
import trezor.messages.MoneroKeyImageSyncStepRequest
import trezor.messages.MoneroLiveRefreshFinalAck
import trezor.messages.MoneroLiveRefreshFinalRequest
import trezor.messages.MoneroLiveRefreshStartAck
import trezor.messages.MoneroLiveRefreshStartRequest
import trezor.messages.MoneroLiveRefreshStepAck
import trezor.messages.MoneroLiveRefreshStepRequest
import trezor.messages.MoneroMultisigKLRki
import trezor.messages.MoneroOutputEntry
import trezor.messages.MoneroRctKeyPublic
import trezor.messages.MoneroRingCtSig
import trezor.messages.MoneroSubAddressIndicesList
import trezor.messages.MoneroTransactionAllInputsSetAck
import trezor.messages.MoneroTransactionAllInputsSetRequest
import trezor.messages.MoneroTransactionAllOutSetAck
import trezor.messages.MoneroTransactionAllOutSetRequest
import trezor.messages.MoneroTransactionData
import trezor.messages.MoneroTransactionDestinationEntry
import trezor.messages.MoneroTransactionFinalAck
import trezor.messages.MoneroTransactionFinalRequest
import trezor.messages.MoneroTransactionInitAck
import trezor.messages.MoneroTransactionInitRequest
import trezor.messages.MoneroTransactionInputViniAck
import trezor.messages.MoneroTransactionInputViniRequest
import trezor.messages.MoneroTransactionInputsPermutationAck
import trezor.messages.MoneroTransactionInputsPermutationRequest
import trezor.messages.MoneroTransactionRsigData
import trezor.messages.MoneroTransactionSetInputAck
import trezor.messages.MoneroTransactionSetInputRequest
import trezor.messages.MoneroTransactionSetOutputAck
import trezor.messages.MoneroTransactionSetOutputRequest
import trezor.messages.MoneroTransactionSignInputAck
import trezor.messages.MoneroTransactionSignInputRequest
import trezor.messages.MoneroTransactionSourceEntry
import trezor.messages.MoneroTransferDetails
import trezor.messages.MoneroWatchKey
import trezor.messages.MultisigRedeemScriptType
import trezor.messages.NEMAddress
import trezor.messages.NEMAggregateModification
import trezor.messages.NEMCosignatoryModification
import trezor.messages.NEMGetAddress
import trezor.messages.NEMImportanceTransfer
import trezor.messages.NEMImportanceTransferMode
import trezor.messages.NEMModificationType
import trezor.messages.NEMMosaic
import trezor.messages.NEMMosaicCreation
import trezor.messages.NEMMosaicDefinition
import trezor.messages.NEMMosaicLevy
import trezor.messages.NEMMosaicSupplyChange
import trezor.messages.NEMProvisionNamespace
import trezor.messages.NEMSignTx
import trezor.messages.NEMSignedTx
import trezor.messages.NEMSupplyChangeType
import trezor.messages.NEMTransactionCommon
import trezor.messages.NEMTransfer
import trezor.messages.NextU2FCounter
import trezor.messages.OutputScriptType
import trezor.messages.OwnershipId
import trezor.messages.OwnershipProof
import trezor.messages.PassphraseAck
import trezor.messages.PassphraseRequest
import trezor.messages.Ping
import trezor.messages.PreauthorizedRequest
import trezor.messages.PrevInput
import trezor.messages.PrevOutput
import trezor.messages.PrevTx
import trezor.messages.PublicKey
import trezor.messages.RecoveryDevice
import trezor.messages.RecoveryDeviceType
import trezor.messages.RequestType
import trezor.messages.ResetDevice
import trezor.messages.RippleAddress
import trezor.messages.RippleGetAddress
import trezor.messages.RipplePayment
import trezor.messages.RippleSignTx
import trezor.messages.RippleSignedTx
import trezor.messages.SafetyCheckLevel
import trezor.messages.SdProtect
import trezor.messages.SdProtectOperationType
import trezor.messages.SetU2FCounter
import trezor.messages.SignIdentity
import trezor.messages.SignMessage
import trezor.messages.SignTx
import trezor.messages.SignedIdentity
import trezor.messages.StellarAccountMergeOp
import trezor.messages.StellarAddress
import trezor.messages.StellarAllowTrustOp
import trezor.messages.StellarAssetType
import trezor.messages.StellarBumpSequenceOp
import trezor.messages.StellarChangeTrustOp
import trezor.messages.StellarCreateAccountOp
import trezor.messages.StellarCreatePassiveOfferOp
import trezor.messages.StellarGetAddress
import trezor.messages.StellarManageDataOp
import trezor.messages.StellarManageOfferOp
import trezor.messages.StellarPathPaymentOp
import trezor.messages.StellarPaymentOp
import trezor.messages.StellarSetOptionsOp
import trezor.messages.StellarSignTx
import trezor.messages.StellarSignedTx
import trezor.messages.StellarTxOpRequest
import trezor.messages.Success
import trezor.messages.TezosAddress
import trezor.messages.TezosBallotOp
import trezor.messages.TezosBallotType
import trezor.messages.TezosContractID
import trezor.messages.TezosContractType
import trezor.messages.TezosDelegationOp
import trezor.messages.TezosGetAddress
import trezor.messages.TezosGetPublicKey
import trezor.messages.TezosManagerTransfer
import trezor.messages.TezosOriginationOp
import trezor.messages.TezosParametersManager
import trezor.messages.TezosProposalOp
import trezor.messages.TezosPublicKey
import trezor.messages.TezosRevealOp
import trezor.messages.TezosSignTx
import trezor.messages.TezosSignedTx
import trezor.messages.TezosTransactionOp
import trezor.messages.TransactionType
import trezor.messages.TxAck
import trezor.messages.TxAckInput
import trezor.messages.TxAckInputWrapper
import trezor.messages.TxAckOutput
import trezor.messages.TxAckOutputWrapper
import trezor.messages.TxAckPrevExtraData
import trezor.messages.TxAckPrevExtraDataWrapper
import trezor.messages.TxAckPrevInput
import trezor.messages.TxAckPrevInputWrapper
import trezor.messages.TxAckPrevMeta
import trezor.messages.TxAckPrevOutput
import trezor.messages.TxAckPrevOutputWrapper
import trezor.messages.TxInput
import trezor.messages.TxInputType
import trezor.messages.TxOutput
import trezor.messages.TxOutputBinType
import trezor.messages.TxOutputType
import trezor.messages.TxRequest
import trezor.messages.TxRequestDetailsType
import trezor.messages.TxRequestSerializedType
import trezor.messages.VerifyMessage
import trezor.messages.WebAuthnAddResidentCredential
import trezor.messages.WebAuthnCredential
import trezor.messages.WebAuthnCredentials
import trezor.messages.WebAuthnListResidentCredentials
import trezor.messages.WebAuthnRemoveResidentCredential
import trezor.messages.WipeDevice
import trezor.messages
import trezor.pin
import trezor.res
import trezor.res.resources
import trezor.sdcard
import trezor.strings
import trezor.ui
import trezor.ui.components
import trezor.ui.components.common
import trezor.ui.components.common.confirm
import trezor.ui.components.common.text
import trezor.ui.components.tt.button
import trezor.ui.components.tt.checklist
import trezor.ui.components.tt.confirm
import trezor.ui.components.tt.info
import trezor.ui.components.tt.num_input
import trezor.ui.components.tt.passphrase
import trezor.ui.components.tt.pin
import trezor.ui.components.tt.scroll
import trezor.ui.components.tt.swipe
import trezor.ui.components.tt.text
import trezor.ui.components.tt.word_select
import trezor.ui.constants
import trezor.ui.constants.t1
import trezor.ui.constants.tt
import trezor.ui.container
import trezor.ui.layouts
import trezor.ui.layouts.common
import trezor.ui.layouts.t1
import trezor.ui.layouts.tt
import trezor.ui.loader
import trezor.ui.popup
import trezor.ui.qr
import trezor.ui.style
import trezor.utils
import trezor.wire
import trezor.wire.codec_v1
import trezor.wire.errors
import trezor.workflow
import apps
import apps.base
import apps.binance
import apps.binance.get_address
import apps.binance.get_public_key
import apps.binance.helpers
import apps.binance.layout
import apps.binance.sign_tx
import apps.bitcoin
import apps.bitcoin.addresses
import apps.bitcoin.authorization
import apps.bitcoin.authorize_coinjoin
import apps.bitcoin.common
import apps.bitcoin.get_address
import apps.bitcoin.get_ownership_id
import apps.bitcoin.get_ownership_proof
import apps.bitcoin.get_public_key
import apps.bitcoin.keychain
import apps.bitcoin.multisig
import apps.bitcoin.ownership
import apps.bitcoin.readers
import apps.bitcoin.scripts
import apps.bitcoin.sign_message
import apps.bitcoin.sign_tx
import apps.bitcoin.sign_tx.approvers
import apps.bitcoin.sign_tx.bitcoin
import apps.bitcoin.sign_tx.bitcoinlike
import apps.bitcoin.sign_tx.decred
import apps.bitcoin.sign_tx.hash143
import apps.bitcoin.sign_tx.helpers
import apps.bitcoin.sign_tx.layout
import apps.bitcoin.sign_tx.matchcheck
import apps.bitcoin.sign_tx.omni
import apps.bitcoin.sign_tx.progress
import apps.bitcoin.sign_tx.tx_info
import apps.bitcoin.sign_tx.tx_weight
import apps.bitcoin.sign_tx.zcash
import apps.bitcoin.verification
import apps.bitcoin.verify_message
import apps.bitcoin.writers
import apps.cardano
import apps.cardano.address
import apps.cardano.byron_address
import apps.cardano.certificates
import apps.cardano.get_address
import apps.cardano.get_public_key
import apps.cardano.helpers
import apps.cardano.helpers.bech32
import apps.cardano.helpers.network_ids
import apps.cardano.helpers.paths
import apps.cardano.helpers.protocol_magics
import apps.cardano.helpers.staking_use_cases
import apps.cardano.helpers.utils
import apps.cardano.layout
import apps.cardano.seed
import apps.cardano.sign_tx
import apps.common
import apps.common.address_type
import apps.common.cbor
import apps.common.coininfo
import apps.common.coins
import apps.common.confirm
import apps.common.keychain
import apps.common.layout
import apps.common.mnemonic
import apps.common.passphrase
import apps.common.paths
import apps.common.readers
import apps.common.request_pin
import apps.common.safety_checks
import apps.common.sdcard
import apps.common.seed
import apps.common.signverify
import apps.common.writers
import apps.debug
import apps.debug.load_device
import apps.debug.show_text
import apps.eos
import apps.eos.actions
import apps.eos.actions.layout
import apps.eos.get_public_key
import apps.eos.helpers
import apps.eos.layout
import apps.eos.sign_tx
import apps.eos.writers
import apps.ethereum
import apps.ethereum.address
import apps.ethereum.get_address
import apps.ethereum.get_public_key
import apps.ethereum.keychain
import apps.ethereum.layout
import apps.ethereum.networks
import apps.ethereum.sign_message
import apps.ethereum.sign_tx
import apps.ethereum.tokens
import apps.ethereum.verify_message
import apps.homescreen
import apps.homescreen.homescreen
import apps.homescreen.lockscreen
import apps.lisk
import apps.lisk.get_address
import apps.lisk.get_public_key
import apps.lisk.helpers
import apps.lisk.layout
import apps.lisk.sign_message
import apps.lisk.sign_tx
import apps.lisk.verify_message
import apps.management
import apps.management.apply_flags
import apps.management.apply_settings
import apps.management.backup_device
import apps.management.backup_types
import apps.management.change_pin
import apps.management.change_wipe_code
import apps.management.get_next_u2f_counter
import apps.management.recovery_device
import apps.management.recovery_device.homescreen
import apps.management.recovery_device.keyboard_bip39
import apps.management.recovery_device.keyboard_slip39
import apps.management.recovery_device.layout
import apps.management.recovery_device.recover
import apps.management.recovery_device.word_validity
import apps.management.reset_device
import apps.management.reset_device.layout
import apps.management.sd_protect
import apps.management.set_u2f_counter
import apps.management.wipe_device
import apps.misc
import apps.misc.cipher_key_value
import apps.misc.get_ecdh_session_key
import apps.misc.get_entropy
import apps.misc.sign_identity
import apps.monero
import apps.monero.diag
import apps.monero.get_address
import apps.monero.get_tx_keys
import apps.monero.get_watch_only
import apps.monero.key_image_sync
import apps.monero.layout.common
import apps.monero.layout.confirms
import apps.monero.live_refresh
import apps.monero.misc
import apps.monero.sign_tx
import apps.monero.signing
import apps.monero.signing.offloading_keys
import apps.monero.signing.state
import apps.monero.signing.step_01_init_transaction
import apps.monero.signing.step_02_set_input
import apps.monero.signing.step_03_inputs_permutation
import apps.monero.signing.step_04_input_vini
import apps.monero.signing.step_05_all_inputs_set
import apps.monero.signing.step_06_set_output
import apps.monero.signing.step_07_all_outputs_set
import apps.monero.signing.step_09_sign_input
import apps.monero.signing.step_10_sign_final
import apps.monero.xmr.addresses
import apps.monero.xmr.bulletproof
import apps.monero.xmr.credentials
import apps.monero.xmr.crypto
import apps.monero.xmr.crypto.chacha_poly
import apps.monero.xmr.keccak_hasher
import apps.monero.xmr.key_image
import apps.monero.xmr.mlsag
import apps.monero.xmr.mlsag_hasher
import apps.monero.xmr.monero
import apps.monero.xmr.networks
import apps.monero.xmr.range_signatures
import apps.monero.xmr.serialize
import apps.monero.xmr.serialize.base_types
import apps.monero.xmr.serialize.int_serialize
import apps.monero.xmr.serialize.message_types
import apps.monero.xmr.serialize.readwriter
import apps.monero.xmr.serialize_messages.base
import apps.monero.xmr.serialize_messages.tx_ct_key
import apps.monero.xmr.serialize_messages.tx_ecdh
import apps.monero.xmr.serialize_messages.tx_prefix
import apps.monero.xmr.serialize_messages.tx_rsig_bulletproof
import apps.monero.xmr.types
import apps.nem
import apps.nem.get_address
import apps.nem.helpers
import apps.nem.layout
import apps.nem.mosaic
import apps.nem.mosaic.helpers
import apps.nem.mosaic.layout
import apps.nem.mosaic.nem_mosaics
import apps.nem.mosaic.serialize
import apps.nem.multisig
import apps.nem.multisig.layout
import apps.nem.multisig.serialize
import apps.nem.namespace
import apps.nem.namespace.layout
import apps.nem.namespace.serialize
import apps.nem.sign_tx
import apps.nem.transfer
import apps.nem.transfer.layout
import apps.nem.transfer.serialize
import apps.nem.validators
import apps.nem.writers
import apps.ripple
import apps.ripple.base58_ripple
import apps.ripple.get_address
import apps.ripple.helpers
import apps.ripple.layout
import apps.ripple.serialize
import apps.ripple.sign_tx
import apps.stellar
import apps.stellar.consts
import apps.stellar.get_address
import apps.stellar.helpers
import apps.stellar.layout
import apps.stellar.operations
import apps.stellar.operations.layout
import apps.stellar.operations.serialize
import apps.stellar.sign_tx
import apps.stellar.writers
import apps.tezos
import apps.tezos.get_address
import apps.tezos.get_public_key
import apps.tezos.helpers
import apps.tezos.layout
import apps.tezos.sign_tx
import apps.webauthn
import apps.webauthn.add_resident_credential
import apps.webauthn.common
import apps.webauthn.confirm
import apps.webauthn.credential
import apps.webauthn.fido2
import apps.webauthn.knownapps
import apps.webauthn.list_resident_credentials
import apps.webauthn.remove_resident_credential
import apps.webauthn.resident_credentials
